### ISSUE TITLE
docker-wordpress multisite configuration

### ISSUE THREAD

**Issue by AngieB** [etopian/docker-wordpress#1]
Hi there, 

I'm really digging docker-wordpress! I was able to get this up and running with 2 separate wordpress containers relatively quickly, but I'm having a bit of trouble trying to configure this for use with wordpress multisite.  I've tried configuring the nginx.conf file within the wordpress container that I have multisite enabled on, which doesn't work; the second site that has been added to the multisite wordpress install gives an nginx 503 error (this is also the case with using the domain mapping plugin). 

Any help or suggestions welcome! 

Thanks! 

Angie

**Comment by etopian** [comment]
When you run the container you have to specify all the domains in the VIRTUAL_HOST parameter. If you want to deploy more sites you have to recreate the container.

**Comment by etopian** [comment]
i.e. docker ... -e VIRTUAL_HOST=site1.com,www.site1.com,site2.com,www.site2.com otherwise nginx proxy will not route to the container. That's what seems to be your problem.

**Comment by etopian** [comment]
btw if you share the nginx file for the multi wp i will add it to the repo. on my todo list, but I don't really like using multi-sites.

**Comment by AngieB** [comment]
Thank you! I was putting in spaces between the domains. No nginx reconfiguring needed. Works perfectly now.
