### ISSUE TITLE
Nginx error 503

### ISSUE THREAD

**Issue by dotMastaz** [etopian/docker-wordpress#6]
Hello,

Thank you for your docker image and instruction.
But when i launch site on ip i have the error :
503 Service Temporarily Unavailable
nginx/1.11.3

Any ideas ?
Thank you !!

**Comment by etopian** [comment]
Did you pull the image from docker hub or did you compile it yourself?

Are you using it behind the nginx proxy or are you running it by itself?

Did you pull the nginx reverse proxy and run it as per instructions.

Also inspect of the containers for nginx proxy and WP would be helpful.

**Comment by dotMastaz** [comment]
Hello, thank you for your fast reply...

I followed all the instructions in this page : http://www.wordpressdocker.com/
And i had the same configuration :
 Docker 1.12.3 on an Ubuntu Xenial 16.04 LTS

Thank you,
Nicolas

**Comment by dotMastaz** [comment]
Re: That's work when i try to access with domain name : etopian.com,...
The error 503 come when i try to access with the ip...

**Comment by etopian** [comment]
ah ok. do not use etopian.com, use your own domain name that is pointed at the ip address of your server.

**Comment by dotMastaz** [comment]
Yes, i just copy/paste all the tuto to see if that works...
I test with my domain and... All works fine !!
Thank you Etopian
