### ISSUE TITLE
Multiple site

### ISSUE THREAD

**Issue by dotMastaz** [etopian/docker-wordpress#7]
Hello,

I created 2 sites (test1.com & test2.com) :

1°
mkdir -p /data/sites/test1.com/htdocs
sudo docker run -e VIRTUAL_HOST=test1.com,www.test1.com -v /data/sites/test1.com:/DATA etopian/alpine-php-wordpress

mkdir -p /data/sites/test2.com/htdocs
sudo docker run -e VIRTUAL_HOST=test2.com,www.test2.com -v /data/sites/test2.com:/DATA etopian/alpine-php-wordpress

2°
Docker Server IP is 196.168.1.45
I test that on windows and add lines in my host file :
192.168.1.45 www.test1.com test1.com
192.168.1.45 www.test2.com test2.com

test1.com is ok.
But test2.com redirect to test2.com ??

Any ideas ?
Thank you !

**Comment by etopian** [comment]
Don't understand test2.com redirects to test2.com? Like in a loop or something?

**Comment by dotMastaz** [comment]
Hello, 

No test2.com redirect to test1.com

**Comment by etopian** [comment]
Look at your wp-config.php file in /data/sites/test2.com/htdocs and make sure it's configured properly for the test2 and not test1. Also add this to it add see if it makes a difference. 
```
define('WP_HOME','http://www.test2.com');
define('WP_SITEURL','http://www.test2.com');
```

It sounds like WP in test2 is configured improperly and is redirecting to the test1 url.

**Comment by dotMastaz** [comment]
I had not put any files in /sites/test2.com/htdocs/ ...

**Comment by etopian** [comment]
How did your start the nginx-proxy container? What's the command you typed?

```
docker run -d --name nginx -p 80:80 -p 443:443 -v /etc/nginx/htpasswd:/etc/nginx/htpasswd -v /etc/nginx/vhost.d:/etc/nginx/vhost.d:ro -v /etc/nginx/certs:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock:ro etopian/nginx-proxy
```

If so check and make sure /etc/nginx/vhost.d is empty.

**Comment by dotMastaz** [comment]
Yes it's this command line.

"vhost.d" on local or docker side ?

**Comment by etopian** [comment]
Local... not inside the container... Not sure how that works on Windows though. Err actually the docker side. Local would be your Windows box I would think.

**Comment by dotMastaz** [comment]
I'm on linux to run docker. I test the sites on windows

Yes, directory vhost.d is empty

**Comment by etopian** [comment]
Okay try to start a third container then test3... make the necessary DNS adjustments there. See what happens then.

**Comment by dotMastaz** [comment]
If i put all wordpress files in test/htdocs with correct wp-config file and domain, that's works.
Just error on install step 2 about mail and phpmailer
![2016-12-02_10-10-57](https://cloud.githubusercontent.com/assets/1413375/20828680/fa365600-b878-11e6-9a71-b2a3f9586b93.jpg)

**Comment by etopian** [comment]
Umm dunno how you installed WP... Usually you provide a valid e-mail address for the admin user. It does not seem as if you provided one hence the error.

**Comment by dotMastaz** [comment]
So, i have well indicated my email adress... Perhaps is about the docker and modules ?

**Comment by etopian** [comment]
How did you install WP?

**Comment by etopian** [comment]
easy way is to enter the container and install it using wp-cli.. 
```
docker exec -it <container_name> bash
su nginx
cd /DATA/htdocs
wp-cli core install ...
```

**Comment by dotMastaz** [comment]
I just create a new use from WordPress admin and i have the same error :

**Comment by etopian** [comment]
Well just ignore it... I think that's because there is no mail server running in the container... look at wordpressdocker.com for instructions how to get the mail to work using the mailgun plugin.

**Comment by dotMastaz** [comment]
Yes i see it and i try to resolve with it, thank you.

About your docker image, i can't use it for just have php7 dev env ?

**Comment by etopian** [comment]
You can. You can fork it and remove the WP stuff and add a custom nginx file.

**Comment by etopian** [comment]
Should work the same depending on your PHP framework...

**Comment by dotMastaz** [comment]
Ok ok,....
And I wanted to thank you for the work. Surely the best docker image for WordPress development !

**Comment by dotMastaz** [comment]
Instead to use mailgun,....
The best way will be to use mail server no ?

**Comment by dotMastaz** [comment]
Perhaps with the use of this docker image ?
https://github.com/tomav/docker-mailserver

**Comment by etopian** [comment]
No... because mail delivery problems. Also it consumes resources on the server. With mailgun you get much better delivery and so you don't have to be running multiple mail servers. I like to keep things easy.

**Comment by etopian** [comment]
Also if you are going to be using this for development on Linux... You need to know how to fix permissions..

```
chown -R 100:101 /data/sites/test1.com // for the container to work properly.
setfacl -Rm u:<user>:rwX,g:<user>:rwX,d:g:<user>:rwX /data/sites/test1.com
```
```
Replace <user> with your username... then you can edit the files from your user account with an editor.
```

**Comment by dotMastaz** [comment]
Etopian could you describe what there lines do... mostly the line 2, thank you

**Comment by etopian** [comment]
https://linux.die.net/man/1/setfacl

http://www.techrepublic.com/blog/linux-and-open-source/learn-to-use-extended-file-attributes-in-linux-to-boost-security/

It sets extended attributes on that folder to allow user read write execute privilege for the user.

The first line changes the user and group to the user and the group of the nginx user inside the container so that the nginx user can write files to the wp-content directory for media uploads.

**Comment by dotMastaz** [comment]
Thank you for these informations, i go to read it !!

**Comment by dotMastaz** [comment]
I just to restart my linux machine and all the container disapeared, normal ?

**Comment by etopian** [comment]
The container does not disappear. Docker does not auto-start containers. You have to start them manually or configure systemd to do it for you.

**Comment by etopian** [comment]
docker ps --all lists all the containers and docker start, starts them.

**Comment by dotMastaz** [comment]
Yesss, you are wonderful !!
Where is your piggy bank for the support ?!

**Comment by etopian** [comment]
I will contact you when I have devoply going and you can help test that. That's support enough. Thanks for using the container.

**Comment by dotMastaz** [comment]
Ok, i try Devolply and there are some erros in register form...

**Comment by etopian** [comment]
Registration is disabled right now. Still a work in progress.

**Comment by dotMastaz** [comment]
Ok, courage !!

**Comment by dotMastaz** [comment]
Re,

I want to use this letsencryt docker : 
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion

What is ":ro" in :
docker run -d -p 80:80 -p 443:443 \
    --name nginx \
    -v /etc/nginx/conf.d  \
    -v /etc/nginx/vhost.d \
    -v /usr/share/nginx/html \
    **-v /path/to/certs:/etc/nginx/certs:ro \**
    nginx

**Comment by etopian** [comment]
certs: /etc/nginx/certs'

but this only works if your server is public. you can not use this privately for a private ip.

**Comment by etopian** [comment]
Any other questions please bring them here: https://gitter.im/etopian/devoply github sucks for chatting.

**Comment by dotMastaz** [comment]
Ok thank you !
